version: '1.0'
services:
  user-service:
    build:
      context: ./user-service
    ports:
      - "8081:5000"
    restart: always
    environment:
      FLASK_ENV: production

  bet-service:
    build:
      context: ./bet-service
    ports:
      - "8082:5001"
    restart: always
    environment:
      FLASK_ENV: production